### ISSUE TITLE
Implement game round logic

### ISSUE THREAD

**Issue by OleaBlossom** [veruspackova/rollenspiel_naturlieblinge#10]
As a user, I want to have a game-round logic, so that I can play as my chosen character. 

AC:

- characters can move up to 2 fields 
- characters perform an action (fight, use or search for items)
- characters can rest and regenerate HP

Still needed:
-search and use were waiting for items
-move and fight were waiting for change in position determination
-fight needs fightround to be fully implemented
--> follow-up story

**Comment by jmalsbenden** [comment]
characters can move up to 2 Fields and performe an action
an action is either to fight, use an item or search for items

the other option is to rest and regenerate hp
